english_word_dict = {
    # Desktop lifecycle and settings
    "settings": "Test settings",
    "browse": "Browse…",
    "action_file": "Action file",
    "engine": "Engine",
    "stop_button": "Stop",
    "idle": "Idle",
    "running": "Running",
    "stopping": "Stopping",
    "completed": "Completed",
    "failed": "Failed",
    "cancelled": "Cancelled",
    "success": "Success",
    "results": "Recent requests",
    "request": "Request",
    "latency": "Latency (ms)",
    "result": "Result",
    "failure_rate": "Failure rate",
    "invalid_input": "Enter an HTTP target and positive load settings.",
    # Main
    "application_name": "LoadDensity",
    # Widget
    "url": "URL",
    "test_time": "Test Time: ",
    "user_count": "User Count: ",
    "spawn_rate": "Spawn Rate: ",
    "test_method": "Test Method: ",
    "start_button": "Start: ",
    # Test method
    "get": "GET",
    "post": "POST",
    "put": "PUT",
    "patch": "PATCH",
    "delete": "DELETE",
    "head": "HEAD",
    "options": "OPTIONS",
    # Stats panel
    "stats_panel": "Live Stats",
    "stats_total": "Total",
    "stats_rate": "Rate",
    "stats_avg_ms": "Avg",
    "stats_p95_ms": "p95",
    "stats_failures": "Failures",
    # Tabs and run history
    "tab_log": "Log",
    "tab_chart": "Live Chart",
    "tab_history": "Run History",
    "history_open_db": "Open DB...",
    "history_refresh": "Refresh",
}
