japanese_word_dict = {
    # Desktop lifecycle and settings
    "settings": "テスト設定",
    "browse": "参照…",
    "action_file": "アクションファイル",
    "engine": "エンジン",
    "stop_button": "停止",
    "idle": "待機",
    "running": "実行中",
    "stopping": "停止中",
    "completed": "完了",
    "failed": "失敗",
    "cancelled": "キャンセル済み",
    "success": "成功",
    "results": "最近のリクエスト",
    "request": "リクエスト",
    "latency": "遅延 (ms)",
    "result": "結果",
    "failure_rate": "失敗率",
    "invalid_input": "HTTP URL と正の負荷設定を入力してください。",
    # Main
    "application_name": "LoadDensity",
    # Widget
    "url": "URL: ",
    "test_time": "テスト時間: ",
    "user_count": "ユーザー数: ",
    "spawn_rate": "生成レート: ",
    "test_method": "HTTP メソッド: ",
    "start_button": "開始: ",
    # Test method
    "get": "GET",
    "post": "POST",
    "put": "PUT",
    "patch": "PATCH",
    "delete": "DELETE",
    "head": "HEAD",
    "options": "OPTIONS",
    # Stats panel
    "stats_panel": "リアルタイム統計",
    "stats_total": "合計",
    "stats_rate": "レート",
    "stats_avg_ms": "平均",
    "stats_p95_ms": "p95",
    "stats_failures": "失敗",
    # Tabs and run history
    "tab_log": "ログ",
    "tab_chart": "ライブチャート",
    "tab_history": "実行履歴",
    "history_open_db": "DB を開く…",
    "history_refresh": "更新",
}
