korean_word_dict = {
    # Desktop lifecycle and settings
    "settings": "테스트 설정",
    "browse": "찾아보기…",
    "action_file": "작업 파일",
    "engine": "엔진",
    "stop_button": "중지",
    "idle": "대기",
    "running": "실행 중",
    "stopping": "중지 중",
    "completed": "완료",
    "failed": "실패",
    "cancelled": "취소됨",
    "success": "성공",
    "results": "최근 요청",
    "request": "요청",
    "latency": "지연 (ms)",
    "result": "결과",
    "failure_rate": "실패율",
    "invalid_input": "HTTP 대상과 양수 부하 설정을 입력하세요.",
    # Main
    "application_name": "LoadDensity",
    # Widget
    "url": "URL: ",
    "test_time": "테스트 시간: ",
    "user_count": "사용자 수: ",
    "spawn_rate": "생성 속도: ",
    "test_method": "HTTP 메서드: ",
    "start_button": "시작: ",
    # Test method
    "get": "GET",
    "post": "POST",
    "put": "PUT",
    "patch": "PATCH",
    "delete": "DELETE",
    "head": "HEAD",
    "options": "OPTIONS",
    # Stats panel
    "stats_panel": "실시간 통계",
    "stats_total": "합계",
    "stats_rate": "속도",
    "stats_avg_ms": "평균",
    "stats_p95_ms": "p95",
    "stats_failures": "실패",
    # Tabs and run history
    "tab_log": "로그",
    "tab_chart": "실시간 차트",
    "tab_history": "실행 기록",
    "history_open_db": "DB 열기…",
    "history_refresh": "새로 고침",
}
