traditional_chinese_word_dict = {
    # Desktop lifecycle and settings
    "settings": "測試設定",
    "browse": "瀏覽…",
    "action_file": "動作檔案",
    "engine": "引擎",
    "stop_button": "停止",
    "idle": "待命",
    "running": "執行中",
    "stopping": "停止中",
    "completed": "已完成",
    "failed": "失敗",
    "cancelled": "已取消",
    "success": "成功",
    "results": "近期請求",
    "request": "請求",
    "latency": "延遲 (ms)",
    "result": "結果",
    "failure_rate": "失敗率",
    "invalid_input": "請輸入 HTTP 目標及正整數負載設定。",
    # Main
    "application_name": "LoadDensity",
    # Widget
    "url": "URL: ",
    "test_time": "測試時間: ",
    "user_count": "測試使用者總數: ",
    "spawn_rate": "產生速率: ",
    "test_method": "測試 HTTP 方法: ",
    "start_button": "開始: ",
    # Test method
    "get": "GET",
    "post": "POST",
    "put": "PUT",
    "patch": "PATCH",
    "delete": "DELETE",
    "head": "HEAD",
    "options": "OPTIONS",
    # Stats panel
    "stats_panel": "即時統計",
    "stats_total": "總計",
    "stats_rate": "速率",
    "stats_avg_ms": "平均",
    "stats_p95_ms": "p95",
    "stats_failures": "失敗",
    # Tabs and run history
    "tab_log": "日誌",
    "tab_chart": "即時圖表",
    "tab_history": "執行紀錄",
    "history_open_db": "開啟資料庫…",
    "history_refresh": "重新整理",
}
