apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master
  labels:
    app.kubernetes.io/name: loaddensity
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: master
spec:
  type: {{ .Values.master.service.type }}
  selector:
    app.kubernetes.io/name: loaddensity
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: master
  ports:
    - name: bind
      port: {{ .Values.master.service.bindPort }}
      targetPort: {{ .Values.master.service.bindPort }}
    - name: web
      port: {{ .Values.master.service.webPort }}
      targetPort: {{ .Values.master.service.webPort }}
