name: LoadDensity Dev Python 3.11

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  schedule:
    - cron: "0 5 * * *"

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev_requirements.txt
      - name: Test Fast HTTP User
        run: python ./test/unit_test/user_test/fast_http_user_test.py
      - name: TestMulti Action User
        run: python ./test/unit_test/user_test/http_user_test.py
      - name: Test Callback
        run: python ./test/unit_test/callback_test/callback_test.py
      - name: Test Create Project
        run: python ./test/unit_test/create_project/create_project.py
      - name: Test Generate HTML Report
        run: python ./test/unit_test/generate_report/generate_html_report.py
      - name: Test Generate XML Report
        run: python ./test/unit_test/generate_report/generate_xml_report.py
      - name: Test Generate JSON Report
        run: python ./test/unit_test/generate_report/generate_json_report.py
      - name: Test Executor
        run: python ./test/unit_test/executor_test/execute.py